[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = ["query_counter"]

[tool.hatch.build.targets.wheel]
packages = ["query_counter"]

[project]
name = "django-query-counter"
version = "0.4.1"
description = "Debug tool to print SQL queries count to the console"
authors = [{name = "Oleg Smedyuk", email = "oleg.smedyuk@gmail.com"}]
license = "MIT"
keywords = ["django", "sql", "query", "count", "management", "commands"]
readme = "README.md"
requires-python = ">= 3.8"

dependencies = [
  "tabulate"
]

classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Web Environment",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Topic :: Utilities",
  "Framework :: Django",
  "Framework :: Django :: 3.2",
  "Framework :: Django :: 4.0",
  "Framework :: Django :: 4.1",
  "Framework :: Django :: 4.2",
  "Framework :: Django :: 5.0",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]

[project.urls]
Homepage = "https://github.com/conformist-mw/django-query-counter"
Changelog = "https://github.com/conformist-mw/django-query-counter/blob/master/CHANGELOG.md"

[tool.tox]
legacy_tox_ini = """
    [tox]
    requires =
        tox>=4.5
    env_list =
      lint
      py312-django{50, 42}
      py311-django{50, 42, 41}
      py310-django{50, 42, 41, 40, 32}
      py39-django{42, 41, 40, 32}
      py38-django{42, 41, 40, 32}

    [testenv]
    deps =
        pytest>=7
        pytest-django
        django32: Django>=3.2,<3.3
        django40: Django>=4.0,<4.1
        django41: Django>=4.1,<4.2
        django42: Django>=4.2,<5.0
        django50: Django>=5.0,<5.1
    set_env =
        PYTHONDEVMODE = 1
    commands = pytest -Wa -r {posargs:.}

    [gh-actions]
    python =
        3.8: py38
        3.9: py39
        3.10: py310
        3.11: py311
        3.12: py312

    [gh-actions:env]
    DJANGO =
        3.2: dj32
        4.0: dj40
        4.1: dj41
        4.2: dj42
        5.0: dj50

    [testenv:lint]
    description = run linters
    skip_install = true
    deps =
        ruff==0.1.13
    commands = ruff {posargs:query_counter}
"""

[tool.ruff]
line-length = 80
fix = false
ignore-init-module-imports = true
select = [
  "E",    # pycodestyle
  "F",    # pyflakes
  "I",    # isort
  "A",    # flake8-builtins
  "COM",  # flake8-commas
  "T20",  # flake8-print
  "Q",    # flake8-quotes
  "BLE",  # flake8-blind-except
  "N",    # pep8-naming
]
[tool.ruff.flake8-quotes]
inline-quotes = "single"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "settings"
pythonpath = "tests"
