name: check

on:
  - push
  - pull_request

jobs:
  tests:
    name: python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'

    steps:
    - uses: actions/checkout@v7

    - name: set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}

    - name: install uv
      uses: astral-sh/setup-uv@v10.2.0
      with:
        enable-cache: true

    - name: Run tox targets for ${{ matrix.python-version }}
      run: uvx --with tox-uv tox run -f py$(echo ${{ matrix.python-version }} | tr -d .)

  lint:
    name: run ruff check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/ruff-action@v4.1.0
        with:
          args: "check"
